name: Prod Deployment
on:
  push:
    branches: [master]

permissions:
  contents: read
  packages: write

jobs:
  build-push:
    strategy:
      matrix:
        service: [frontend, backend]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: operaoflife
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: ./${{ matrix.service }}
        push: true
        tags: |
          ghcr.io/operaoflife/prod-${{ matrix.service }}:latest
          ghcr.io/operaoflife/prod-${{ matrix.service }}:${{ github.sha }}
        file: ./${{ matrix.service }}/Dockerfile