apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ci-cd
  labels:
    app: frontend
    env: production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        env: production
    spec:
      containers:
      - name: frontend
        image: ghcr.io/operaoflife/prod-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ENV
          value: "prod"
        - name: VITE_API_URL
          value: "http://backend-service.ci-cd.svc.cluster.local/api"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 45
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5