name: Dev Deployment
on:
  push:
    branches: [develop]

jobs:
  build-push:
    strategy:
      matrix:
        service: [frontend, backend]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Docker Build/Push
      uses: docker/build-push-action@v4
      with:
        context: ./${{ matrix.service }}
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/dev-${{ matrix.service }}:latest
          ghcr.io/${{ github.repository_owner }}/dev-${{ matrix.service }}:${{ github.sha }}
        file: ./${{ matrix.service }}/Dockerfile

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/
      env:
        KUBECONFIG: ${{ secrets.KUBE_CONFIG }}