# .github/workflows/docker-prod.yml
name: Publish Prod Image

permissions:
  contents: read      # for checkout
  packages: write     # to push to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU (for cross-platform builds)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract image metadata (tags & labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/myapp

      - name: Build & push prod image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/myapp:latest
            ghcr.io/${{ github.repository }}/myapp:prod-${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
