# .github/workflows/publish-ghcr.yml
name: Publish to GitHub Container Registry

# triggers when you push to master (or change to main if that’s your primary branch)
on:
  push:
    branches:
      - master

permissions:
  contents: read       # needed to checkout code
  packages: write      # needed to push to GHCR

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out your code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract image metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          # point at your GHCR namespace/repo
          images: ghcr.io/${{ github.repository }}/testnodejsapp

      - name: Build & push image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
