name: Prod Deployment
on:
  push:
    branches: [master]

env:
  REGISTRY: ghcr.io
  GITHUB_USER: your-github-username
  CLUSTER_NAME: prod-cluster
  ZONE: us-central1-c

jobs:
  build-push:
    strategy:
      matrix:
        service: [frontend, backend]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Docker Build/Push
      uses: docker/build-push-action@v4
      with:
        context: ./${{ matrix.service }}
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.GITHUB_USER }}/prod-${{ matrix.service }}:latest
          ${{ env.REGISTRY }}/${{ env.GITHUB_USER }}/prod-${{ matrix.service }}:${{ github.sha }}
        file: ./${{ matrix.service }}/Dockerfile

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
    - name: Setup GCP
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to Production
      run: |
        gcloud container clusters get-credentials $CLUSTER_NAME --zone $ZONE
        kubectl apply -f k8s/
        kubectl rollout restart deployment/frontend
        kubectl rollout restart deployment/backend