name: Publish Docker image (Prod)

on:
  push:
    branches: ['master']

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry (Prod)
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker (Prod)
        id: meta
        uses: docker/metadata-action@v4
        with:
          registry: ghcr.io
          # we’ll tag as ghcr.io/OWNER/REPO-prod:...
          images: ghcr.io/${{ github.repository }}-prod
      
      - name: Build and push Docker image (Prod)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
