apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ci-cd
  labels:
    app: backend
    env: production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        env: production
    spec:
      containers:
      - name: backend
        image: ghcr.io/operaoflife/prod-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: ENV
          value: "prod"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10