apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ci-cd
spec:  # Remove the annotations block
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: http
    port: 80
    targetPort: 3000