apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ci-cd
  annotations:
    cloud.google.com/backend-config: '{"default": "backend-config"}'
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: http
    port: 80
    targetPort: 3000